namespace CargoHub.Domain.Bookings;

/// <summary>
/// Core booking aggregate.
/// This mirrors the structure of IBookingRecord / IBaseBooking in the existing Node.js backend
/// in a relational, strongly typed way suitable for EF Core.
/// </summary>
public class Booking
{
    /// <summary>
    /// Primary key generated by the database.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Identifier of the customer who owns this booking.
    /// This corresponds to the customer-id used in the current system.
    /// </summary>
    public string CustomerId { get; set; } = string.Empty;

    /// <summary>
    /// Company this booking belongs to (set on create from user's company). Used for form config scope and cascade on company delete.
    /// </summary>
    public Guid? CompanyId { get; set; }

    /// <summary>
    /// Identifier of the plugin that created the booking.
    /// </summary>
    public string? PluginId { get; set; }

    /// <summary>
    /// Free-form external reference used by integrations.
    /// </summary>
    public string? ExternalId { get; set; }

    /// <summary>
    /// When true, the booking is a draft: user can retrieve, fill in the rest, and confirm to complete.
    /// When false, the booking is completed (normal list/detail).
    /// </summary>
    public bool IsDraft { get; set; }

    /// <summary>
    /// Indicates whether the booking is active/enabled.
    /// Mirrors the enabled flag in the MongoDB model.
    /// </summary>
    public bool Enabled { get; set; } = true;

    /// <summary>
    /// Customer- or system-generated shipment number used for tracking.
    /// </summary>
    public string? ShipmentNumber { get; set; }

    /// <summary>
    /// Optional waybill number used by some carriers.
    /// </summary>
    public string? WaybillNumber { get; set; }

    /// <summary>
    /// Human readable name of the customer; this is denormalised for convenience.
    /// </summary>
    public string? CustomerName { get; set; }

    /// <summary>
    /// Flag describing whether this was created as a test booking.
    /// </summary>
    public bool IsTestBooking { get; set; }

    /// <summary>
    /// Flag used by the portal UI to mark favourite bookings for quick access.
    /// </summary>
    public bool IsFavourite { get; set; }

    /// <summary>
    /// Base64 encoded label PDF for carriers that return PDF content directly.
    /// </summary>
    public string? Base64Pdf { get; set; }

    /// <summary>
    /// Optional estimated time of arrival as epoch seconds.
    /// </summary>
    public long? EtaSeconds { get; set; }

    /// <summary>
    /// UTC creation timestamp used for sorting and filtering.
    /// </summary>
    public DateTime CreatedAtUtc { get; set; }

    /// <summary>
    /// UTC when the booking first became non-draft; set once for subscription volume / pricing anchor.
    /// </summary>
    public DateTime? FirstBillableAtUtc { get; set; }

    /// <summary>
    /// UTC last update timestamp for auditing.
    /// </summary>
    public DateTime UpdatedAtUtc { get; set; }

    /// <summary>
    /// Embedded booking header information (sender, receiver, metadata).
    /// </summary>
    public BookingHeader Header { get; set; } = new();

    /// <summary>
    /// Embedded shipment information such as service, parcels and carrier identifiers.
    /// </summary>
    public BookingShipment Shipment { get; set; } = new();

    /// <summary>
    /// Shipper party details.
    /// </summary>
    public BookingParty Shipper { get; set; } = new();

    /// <summary>
    /// Receiver party details.
    /// </summary>
    public BookingParty Receiver { get; set; } = new();

    /// <summary>
    /// Optional payer party details for freight invoices.
    /// </summary>
    public BookingParty? Payer { get; set; }

    /// <summary>
    /// Address details for pickup.
    /// </summary>
    public BookingParty PickUpAddress { get; set; } = new();

    /// <summary>
    /// Address details for final delivery.
    /// </summary>
    public BookingParty DeliveryPoint { get; set; } = new();

    /// <summary>
    /// Shipping information including total weight, volume and package collection.
    /// Concrete package type is selected per carrier in the existing system;
    /// here we store the main shared fields and leave per-carrier specifics
    /// for specialised tables or JSON columns.
    /// </summary>
    public ShippingInfo ShippingInfo { get; set; } = new();

    /// <summary>
    /// One or more packages in this booking. User can add as many as needed.
    /// </summary>
    public ICollection<BookingPackage> Packages { get; set; } = new List<BookingPackage>();

    /// <summary>
    /// Updates received from external transport systems (tracking, statuses).
    /// </summary>
    public ICollection<BookingUpdate> Updates { get; set; } = new List<BookingUpdate>();

}

/// <summary>
/// A single package within a booking. A booking can have multiple packages.
/// </summary>
public class BookingPackage
{
    public int Id { get; set; }
    public string? Weight { get; set; }
    public string? Volume { get; set; }
    public string? PackageType { get; set; }
    public string? Description { get; set; }
    public string? Length { get; set; }
    public string? Width { get; set; }
    public string? Height { get; set; }
}

/// <summary>
/// High level header information shared by all bookings.
/// </summary>
public class BookingHeader
{
    public string SenderId { get; set; } = string.Empty;
    public string? CompanyId { get; set; }
    public string? ReferenceNumber { get; set; }
    public string? CustomerReference { get; set; }
    public string? PostalService { get; set; }
}

/// <summary>
/// Shipment information that ties the booking to carrier specific data.
/// </summary>
public class BookingShipment
{
    public string? Service { get; set; }
    public string? CarrierId { get; set; }
    public DateTime? ShipmentDateTimeUtc { get; set; }
    public int ParcelCount { get; set; }
    public string? SenderReference { get; set; }
    public string? ReceiverReference { get; set; }
    public string? FreightPayer { get; set; }
    public string? HandlingInstructions { get; set; }
}

/// <summary>
/// Generic party representation (shipper, receiver, payer, pickup, delivery).
/// </summary>
public class BookingParty
{
    public string Name { get; set; } = string.Empty;
    public string Address1 { get; set; } = string.Empty;
    public string? Address2 { get; set; }
    public string PostalCode { get; set; } = string.Empty;
    public string City { get; set; } = string.Empty;
    public string Country { get; set; } = string.Empty;
    public string? Email { get; set; }
    public string? PhoneNumber { get; set; }
    public string? PhoneNumberMobile { get; set; }
    public string? ContactPersonName { get; set; }
    public string? VatNo { get; set; }
    public string? CustomerNumber { get; set; }
}

/// <summary>
/// Shipping information and instructions plus aggregated package level data.
/// </summary>
public class ShippingInfo
{
    public string GrossWeight { get; set; } = "0";
    public string GrossVolume { get; set; } = "0";
    public string PackageQuantity { get; set; } = "0";
    public string? PickupHandlingInstructions { get; set; }
    public string? DeliveryHandlingInstructions { get; set; }
    public string? GeneralInstructions { get; set; }
    public string? ServiceSpecification { get; set; }
    public string? NoDgPackages { get; set; }
    public bool DeliveryWithoutSignature { get; set; }
    public string? LoadMeter { get; set; }
    public string? RouteInformation { get; set; }
}

/// <summary>
/// Update message representing tracking or status information
/// coming from external transport systems (Youredi integrations).
/// </summary>
public class BookingUpdate
{
    public int Id { get; set; }
    public string Status { get; set; } = string.Empty;
    public string? TransportPhase { get; set; }
    public string? RawMessage { get; set; }
    public DateTime CreatedAtUtc { get; set; }
}

