// <auto-generated />
using System;
using CargoHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CargoHub.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CargoHub.Domain.Billing.BillingLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyBillingPeriodId")
                        .HasColumnType("uuid");

                    b.Property<string>("Component")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("ExcludedFromInvoice")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("InvoiceExclusionUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceExclusionUpdatedByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("LineType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubscriptionPlanPricingPeriodId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("IX_BillingLineItems_BookingId");

                    b.HasIndex("CompanyBillingPeriodId")
                        .HasDatabaseName("IX_BillingLineItems_CompanyBillingPeriodId");

                    b.ToTable("BillingLineItems", "companies");
                });

            modelBuilder.Entity("CargoHub.Domain.Billing.BillingPeriodExcludedBooking", b =>
                {
                    b.Property<Guid>("CompanyBillingPeriodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.HasKey("CompanyBillingPeriodId", "BookingId");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("IX_BillingPeriodExcludedBookings_BookingId");

                    b.ToTable("BillingPeriodExcludedBookings", "companies");
                });

            modelBuilder.Entity("CargoHub.Domain.Billing.CompanyBillingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("MonthUtc")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("YearUtc")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "YearUtc", "MonthUtc")
                        .IsUnique()
                        .HasDatabaseName("IX_CompanyBillingPeriods_Company_Year_Month");

                    b.ToTable("CompanyBillingPeriods", "companies");
                });

            modelBuilder.Entity("CargoHub.Domain.Billing.CompanySubscriptionAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SetByUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "EffectiveFromUtc")
                        .HasDatabaseName("IX_CompanySubscriptionAssignments_Company_EffectiveFrom");

                    b.ToTable("CompanySubscriptionAssignments", "companies");
                });

            modelBuilder.Entity("CargoHub.Domain.Billing.SubscriptionInvoiceSend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyBillingPeriodId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("InvoiceTotalSnapshot")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("LedgerTotalSnapshot")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("RecipientAdminUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RecipientEmailSnapshot")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SentBySuperAdminUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyBillingPeriodId")
                        .HasDatabaseName("IX_SubscriptionInvoiceSends_CompanyBillingPeriodId");

                    b.ToTable("SubscriptionInvoiceSends", "companies");
                });

            modelBuilder.Entity("CargoHub.Domain.Billing.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChargeTimeAnchor")
                        .HasColumnType("integer");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("TrialBookingAllowance")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_SubscriptionPlans_IsActive");

                    b.ToTable("SubscriptionPlans", "companies");
                });

            modelBuilder.Entity("CargoHub.Domain.Billing.SubscriptionPlanPricingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ChargePerBooking")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IncludedBookingsPerMonth")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MonthlyFee")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("OverageChargePerBooking")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid>("SubscriptionPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanId", "EffectiveFromUtc")
                        .IsUnique()
                        .HasDatabaseName("IX_SubscriptionPlanPricingPeriods_Plan_EffectiveFrom");

                    b.ToTable("SubscriptionPlanPricingPeriods", "companies");
                });

            modelBuilder.Entity("CargoHub.Domain.Billing.SubscriptionPlanPricingTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ChargePerBooking")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int?>("InclusiveMaxBookingsInPeriod")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MonthlyFee")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubscriptionPlanPricingPeriodId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionPlanPricingPeriodId", "Ordinal")
                        .IsUnique()
                        .HasDatabaseName("IX_SubscriptionPlanPricingTiers_Period_Ordinal");

                    b.ToTable("SubscriptionPlanPricingTiers", "companies");
                });

            modelBuilder.Entity("CargoHub.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Base64Pdf")
                        .HasColumnType("text");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<long?>("EtaSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FirstBillableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FreelanceRiderAcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FreelanceRiderAssignmentDeadlineUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("FreelanceRiderAssignmentLapsed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("FreelanceRiderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTestBooking")
                        .HasColumnType("boolean");

                    b.Property<string>("PluginId")
                        .HasColumnType("text");

                    b.Property<string>("ShipmentNumber")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WaybillNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FreelanceRiderAssignmentDeadlineUtc")
                        .HasDatabaseName("IX_Bookings_FreelanceRiderAssignmentDeadlineUtc");

                    b.HasIndex("FreelanceRiderId");

                    b.HasIndex("ShipmentNumber")
                        .HasDatabaseName("IX_Bookings_ShipmentNumber");

                    b.HasIndex("CompanyId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Bookings_CompanyId_CreatedAtUtc");

                    b.HasIndex("CompanyId", "FirstBillableAtUtc")
                        .HasDatabaseName("IX_Bookings_CompanyId_FirstBillableAtUtc");

                    b.HasIndex("CustomerId", "Enabled", "CreatedAtUtc")
                        .HasDatabaseName("IX_Bookings_Customer_Enabled_CreatedAt");

                    b.HasIndex("CustomerId", "IsDraft", "CreatedAtUtc")
                        .HasDatabaseName("IX_Bookings_Customer_IsDraft_CreatedAt");

                    b.ToTable("Bookings", "bookings");
                });

            modelBuilder.Entity("CargoHub.Domain.Bookings.BookingStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("IX_BookingStatusHistory_BookingId");

                    b.HasIndex("BookingId", "Status")
                        .HasDatabaseName("IX_BookingStatusHistory_BookingId_Status");

                    b.ToTable("BookingStatusHistory", "bookings");
                });

            modelBuilder.Entity("CargoHub.Domain.Bookings.DailyDigestSendLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DigestDateLocal")
                        .HasColumnType("date");

                    b.Property<DateTime>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "DigestDateLocal", "TimeZoneId")
                        .IsUnique()
                        .HasDatabaseName("IX_DailyDigestSendLogs_Company_Date_Tz");

                    b.ToTable("DailyDigestSendLogs", "bookings");
                });

            modelBuilder.Entity("CargoHub.Domain.Companies.BookingImportFileMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColumnMapJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileNameKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("HeaderSignature")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "FileNameKey", "HeaderSignature")
                        .IsUnique()
                        .HasDatabaseName("IX_BookingImportFileMappings_Company_File_Headers");

                    b.ToTable("BookingImportFileMappings", "companies");
                });

            modelBuilder.Entity("CargoHub.Domain.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AdminInviteFirstAcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BusinessId")
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Counter")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DivisionCode")
                        .HasColumnType("text");

                    b.Property<string>("InitialAdminInviteEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("InitialAdminInviteEmailsJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxAdminAccounts")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxUserAccounts")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("SenderNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("SubscriptionPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_Companies_CompanyId");

                    b.HasIndex("SubscriptionPlanId")
                        .HasDatabaseName("IX_Companies_SubscriptionPlanId");

                    b.ToTable("Companies", "companies");
                });

            modelBuilder.Entity("CargoHub.Domain.Companies.CompanyAdminInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_CompanyAdminInvites_CompanyId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_CompanyAdminInvites_TokenHash");

                    b.ToTable("CompanyAdminInvites", "companies");
                });

            modelBuilder.Entity("CargoHub.Domain.FreelanceRiders.FreelanceRider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .HasDatabaseName("IX_FreelanceRiders_ApplicationUserId");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_FreelanceRiders_CompanyId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("IX_FreelanceRiders_NormalizedEmail");

                    b.ToTable("FreelanceRiders", "couriers");
                });

            modelBuilder.Entity("CargoHub.Domain.FreelanceRiders.FreelanceRiderInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FreelanceRiderId")
                        .HasColumnType("uuid");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("FreelanceRiderId")
                        .HasDatabaseName("IX_FreelanceRiderInvites_FreelanceRiderId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_FreelanceRiderInvites_TokenHash");

                    b.ToTable("FreelanceRiderInvites", "couriers");
                });

            modelBuilder.Entity("CargoHub.Domain.FreelanceRiders.FreelanceRiderServiceArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FreelanceRiderId")
                        .HasColumnType("uuid");

                    b.Property<string>("PostalCodeNormalized")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("FreelanceRiderId", "PostalCodeNormalized")
                        .IsUnique()
                        .HasDatabaseName("IX_FreelanceRiderServiceAreas_Rider_Postal");

                    b.ToTable("FreelanceRiderServiceAreas", "couriers");
                });

            modelBuilder.Entity("CargoHub.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("BusinessId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("CustomerMappingId")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("GsOne")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Theme")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "auth");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "auth");
                });

            modelBuilder.Entity("CargoHub.Domain.Billing.BillingLineItem", b =>
                {
                    b.HasOne("CargoHub.Domain.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CargoHub.Domain.Billing.CompanyBillingPeriod", "CompanyBillingPeriod")
                        .WithMany("LineItems")
                        .HasForeignKey("CompanyBillingPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyBillingPeriod");
                });

            modelBuilder.Entity("CargoHub.Domain.Billing.BillingPeriodExcludedBooking", b =>
                {
                    b.HasOne("CargoHub.Domain.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CargoHub.Domain.Billing.CompanyBillingPeriod", "CompanyBillingPeriod")
                        .WithMany("ExcludedBookings")
                        .HasForeignKey("CompanyBillingPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyBillingPeriod");
                });

            modelBuilder.Entity("CargoHub.Domain.Billing.CompanyBillingPeriod", b =>
                {
                    b.HasOne("CargoHub.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CargoHub.Domain.Billing.CompanySubscriptionAssignment", b =>
                {
                    b.HasOne("CargoHub.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CargoHub.Domain.Billing.SubscriptionInvoiceSend", b =>
                {
                    b.HasOne("CargoHub.Domain.Billing.CompanyBillingPeriod", "CompanyBillingPeriod")
                        .WithMany("InvoiceSends")
                        .HasForeignKey("CompanyBillingPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyBillingPeriod");
                });

            modelBuilder.Entity("CargoHub.Domain.Billing.SubscriptionPlanPricingPeriod", b =>
                {
                    b.HasOne("CargoHub.Domain.Billing.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("PricingPeriods")
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("CargoHub.Domain.Billing.SubscriptionPlanPricingTier", b =>
                {
                    b.HasOne("CargoHub.Domain.Billing.SubscriptionPlanPricingPeriod", "PricingPeriod")
                        .WithMany("Tiers")
                        .HasForeignKey("SubscriptionPlanPricingPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PricingPeriod");
                });

            modelBuilder.Entity("CargoHub.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("CargoHub.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CargoHub.Domain.FreelanceRiders.FreelanceRider", null)
                        .WithMany()
                        .HasForeignKey("FreelanceRiderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("CargoHub.Domain.Bookings.BookingParty", "DeliveryPoint", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address1")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Address2")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ContactPersonName")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CustomerNumber")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumberMobile")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("VatNo")
                                .HasColumnType("text");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings", "bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("CargoHub.Domain.Bookings.BookingParty", "Payer", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address1")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Address2")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ContactPersonName")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CustomerNumber")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumberMobile")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("VatNo")
                                .HasColumnType("text");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings", "bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("CargoHub.Domain.Bookings.BookingParty", "PickUpAddress", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address1")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Address2")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ContactPersonName")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CustomerNumber")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumberMobile")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("VatNo")
                                .HasColumnType("text");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings", "bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("CargoHub.Domain.Bookings.BookingParty", "Receiver", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address1")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Address2")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ContactPersonName")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CustomerNumber")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumberMobile")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("VatNo")
                                .HasColumnType("text");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings", "bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("CargoHub.Domain.Bookings.BookingParty", "Shipper", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address1")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Address2")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ContactPersonName")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CustomerNumber")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumberMobile")
                                .HasColumnType("text");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("VatNo")
                                .HasColumnType("text");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings", "bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("CargoHub.Domain.Bookings.BookingHeader", "Header", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CompanyId")
                                .HasColumnType("text");

                            b1.Property<string>("CustomerReference")
                                .HasColumnType("text");

                            b1.Property<string>("PostalService")
                                .HasColumnType("text");

                            b1.Property<string>("ReferenceNumber")
                                .HasColumnType("text");

                            b1.Property<string>("SenderId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings", "bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsMany("CargoHub.Domain.Bookings.BookingPackage", "Packages", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<string>("Height")
                                .HasColumnType("text");

                            b1.Property<string>("Length")
                                .HasColumnType("text");

                            b1.Property<string>("PackageType")
                                .HasColumnType("text");

                            b1.Property<string>("Volume")
                                .HasColumnType("text");

                            b1.Property<string>("Weight")
                                .HasColumnType("text");

                            b1.Property<string>("Width")
                                .HasColumnType("text");

                            b1.HasKey("BookingId", "Id");

                            b1.ToTable("BookingPackage", "bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("CargoHub.Domain.Bookings.BookingShipment", "Shipment", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CarrierId")
                                .HasColumnType("text");

                            b1.Property<string>("FreightPayer")
                                .HasColumnType("text");

                            b1.Property<string>("HandlingInstructions")
                                .HasColumnType("text");

                            b1.Property<int>("ParcelCount")
                                .HasColumnType("integer");

                            b1.Property<string>("ReceiverReference")
                                .HasColumnType("text");

                            b1.Property<string>("SenderReference")
                                .HasColumnType("text");

                            b1.Property<string>("Service")
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ShipmentDateTimeUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings", "bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsMany("CargoHub.Domain.Bookings.BookingUpdate", "Updates", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<DateTime>("CreatedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("RawMessage")
                                .HasColumnType("text");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("TransportPhase")
                                .HasColumnType("text");

                            b1.HasKey("BookingId", "Id");

                            b1.ToTable("BookingUpdate", "bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("CargoHub.Domain.Bookings.ShippingInfo", "ShippingInfo", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DeliveryHandlingInstructions")
                                .HasColumnType("text");

                            b1.Property<bool>("DeliveryWithoutSignature")
                                .HasColumnType("boolean");

                            b1.Property<string>("GeneralInstructions")
                                .HasColumnType("text");

                            b1.Property<string>("GrossVolume")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("GrossWeight")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("LoadMeter")
                                .HasColumnType("text");

                            b1.Property<string>("NoDgPackages")
                                .HasColumnType("text");

                            b1.Property<string>("PackageQuantity")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PickupHandlingInstructions")
                                .HasColumnType("text");

                            b1.Property<string>("RouteInformation")
                                .HasColumnType("text");

                            b1.Property<string>("ServiceSpecification")
                                .HasColumnType("text");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings", "bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("DeliveryPoint")
                        .IsRequired();

                    b.Navigation("Header")
                        .IsRequired();

                    b.Navigation("Packages");

                    b.Navigation("Payer");

                    b.Navigation("PickUpAddress")
                        .IsRequired();

                    b.Navigation("Receiver")
                        .IsRequired();

                    b.Navigation("Shipment")
                        .IsRequired();

                    b.Navigation("Shipper")
                        .IsRequired();

                    b.Navigation("ShippingInfo")
                        .IsRequired();

                    b.Navigation("Updates");
                });

            modelBuilder.Entity("CargoHub.Domain.Bookings.DailyDigestSendLog", b =>
                {
                    b.HasOne("CargoHub.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CargoHub.Domain.Companies.BookingImportFileMapping", b =>
                {
                    b.HasOne("CargoHub.Domain.Companies.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CargoHub.Domain.Companies.Company", b =>
                {
                    b.HasOne("CargoHub.Domain.Billing.SubscriptionPlan", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("CargoHub.Domain.Companies.AgreementNumber", "AgreementNumbers", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("Counter")
                                .HasColumnType("integer");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PostalService")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Service")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("CompanyId");

                            b1.ToTable("AgreementNumber", "companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsMany("CargoHub.Domain.Companies.CompanyAddress", "AddressBook", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Address1")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Address2")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContactPersonName")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("County")
                                .HasColumnType("text");

                            b1.Property<string>("CustomerNumber")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("text");

                            b1.Property<bool>("PhoneNumberMobile")
                                .HasColumnType("boolean");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("VatNo")
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("CompanyId");

                            b1.ToTable("Companies_AddressBook", "companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("CargoHub.Domain.Companies.CompanyAddress", "DefaultShipperAddress", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Address1")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Address2")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ContactPersonName")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("County")
                                .HasColumnType("text");

                            b1.Property<string>("CustomerNumber")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("text");

                            b1.Property<bool>("PhoneNumberMobile")
                                .HasColumnType("boolean");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("VatNo")
                                .HasColumnType("text");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies", "companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsMany("CargoHub.Domain.Companies.CompanyAddress", "PickUpAddressBook", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Address1")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Address2")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContactPersonName")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("County")
                                .HasColumnType("text");

                            b1.Property<string>("CustomerNumber")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("text");

                            b1.Property<bool>("PhoneNumberMobile")
                                .HasColumnType("boolean");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("VatNo")
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("CompanyId");

                            b1.ToTable("Companies_PickUpAddressBook", "companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsMany("CargoHub.Domain.Companies.CompanyAddress", "SenderAddressBook", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Address1")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Address2")
                                .HasColumnType("text");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContactPersonName")
                                .HasColumnType("text");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("County")
                                .HasColumnType("text");

                            b1.Property<string>("CustomerNumber")
                                .HasColumnType("text");

                            b1.Property<string>("Email")
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("text");

                            b1.Property<bool>("PhoneNumberMobile")
                                .HasColumnType("boolean");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("VatNo")
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("CompanyId");

                            b1.ToTable("Companies_SenderAddressBook", "companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("CargoHub.Domain.Companies.CompanyConfiguration", "Configurations", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BookingFieldRulesJson")
                                .HasColumnType("text");

                            b1.Property<string>("DefaultPostalService")
                                .HasColumnType("text");

                            b1.Property<string>("FreightPayer")
                                .HasColumnType("text");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("text");

                            b1.Property<string>("PickUpAddressVatNo")
                                .HasColumnType("text");

                            b1.Property<string>("Service")
                                .HasColumnType("text");

                            b1.Property<string>("ShipperVatNo")
                                .HasColumnType("text");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies", "companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("AddressBook");

                    b.Navigation("AgreementNumbers");

                    b.Navigation("Configurations");

                    b.Navigation("DefaultShipperAddress");

                    b.Navigation("PickUpAddressBook");

                    b.Navigation("SenderAddressBook");
                });

            modelBuilder.Entity("CargoHub.Domain.Companies.CompanyAdminInvite", b =>
                {
                    b.HasOne("CargoHub.Domain.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CargoHub.Domain.FreelanceRiders.FreelanceRider", b =>
                {
                    b.HasOne("CargoHub.Domain.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CargoHub.Domain.FreelanceRiders.FreelanceRiderInvite", b =>
                {
                    b.HasOne("CargoHub.Domain.FreelanceRiders.FreelanceRider", "FreelanceRider")
                        .WithMany()
                        .HasForeignKey("FreelanceRiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FreelanceRider");
                });

            modelBuilder.Entity("CargoHub.Domain.FreelanceRiders.FreelanceRiderServiceArea", b =>
                {
                    b.HasOne("CargoHub.Domain.FreelanceRiders.FreelanceRider", "FreelanceRider")
                        .WithMany("ServiceAreas")
                        .HasForeignKey("FreelanceRiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FreelanceRider");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CargoHub.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CargoHub.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CargoHub.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CargoHub.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CargoHub.Domain.Billing.CompanyBillingPeriod", b =>
                {
                    b.Navigation("ExcludedBookings");

                    b.Navigation("InvoiceSends");

                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("CargoHub.Domain.Billing.SubscriptionPlan", b =>
                {
                    b.Navigation("PricingPeriods");
                });

            modelBuilder.Entity("CargoHub.Domain.Billing.SubscriptionPlanPricingPeriod", b =>
                {
                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("CargoHub.Domain.FreelanceRiders.FreelanceRider", b =>
                {
                    b.Navigation("ServiceAreas");
                });
#pragma warning restore 612, 618
        }
    }
}
